server {
    listen 8080;
    server_name localhost;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # This is the magic line that fixes the 404 for React Router!
        try_files $uri $uri/ /index.html;
    }

    # 2. Proxy User API requests to the backend microservice
    location /api/users {
        # Kubernetes magically routes 'user-service' to your backend pod!
        proxy_pass http://user-service:8081/api/users;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}