apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      # DEVSECOPS TRICK: Grant the nonroot user permission to write uploads!
      securityContext:
        fsGroup: 65532
      containers:
      - name: product-service
        # Point to your Azure ACR!
        image: it22246714ctse.azurecr.io/product-service:latest
        imagePullPolicy: Always
        # --- ADD THIS ENV BLOCK ---
        env:
        - name: PORT
          value: "5000"
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: product-secret
              key: mongo-uri
        # --------------------------
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: upload-storage
          mountPath: /app/uploads
      volumes:
      - name: upload-storage
        # emptyDir is much safer for cloud cluster assignments
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000